{% set name = "extras" %}
{% set version = "1.0.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "132e36de10b9c91d5d4cc620160a476e0468a88f16c9431817a6729611a81b4e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python

  run:
    - python

test:
  imports:
    - extras
    - extras.tests

about:
  home: https://github.com/testing-cabal/extras
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'Useful extra bits for Python - things that shold be in the standard library'
  dev_url: https://github.com/testing-cabal/extras
  doc_url: https://github.com/testing-cabal/extras

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
