travis:
  secure:
    BINSTAR_TOKEN: WiQClUkEGnCxca2U55CGVF2Z7dFZo1ZOC84v68EPWPaF29A+zLNdFg3wzcFa2PNYdui919F6H4+cjmWomY2uO5fmmmLMngf3ObE93W++jmjiKTHPlfdI3fwLBU/slGp5UN745eBpDGbK4+sglld8Y36skgr7xcRsCv9vK7P9ByLLblyqjHql4P2EXBFjzfwUW5dkrw4K7uWDviLFfmWveGyaC01KIXiN1DJxypmRWfvP58r8CJq+U7m4E6U2coU91Zec4CDms0ZLbiOrfiizrPeo+sw+ikw4E6Fbfoz1LwHrqqbLAwimhHGZQVSVeE2prF0IPhky0tyX02SU4CeyrJOIf/fkbdmdCdEU8u9aGzZGWKEFnU41P8ri2ScoQ94V7kQiR4PAbKny6xKKpGY6jAPJAYra3qyxeSx5yVg3ka3Y5F9CLkK3DmxMHx/vy9KW5VcNZSdnVOUeu5tOITk20iD0uivrzmvmrGlSrr50MTIHAnQ5jajVjqWXkiHXWAHy2WLTFkF2m7eE2iaBS8rsr5wZrmheKPAJkgQxaB4VPP1EQdBLgYAp03aJjq2lQkmVKwNZnBGJA4Mehu+OuR9OmeDwABP9ITw0OVW7MqOaI4oXqhexIJx0ihfCYqeB4zFfoRxrmsJpm6we8mG8u6GqY9vVAd30yc/Wix8sg5X9Tss=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
