travis:
  secure:
    BINSTAR_TOKEN: Gl0GLKrIJhsfDo5slrTPiYiviDhSpLQaNMMRp517ONMJERaASziti/CsuUwDwvQEbS2BMRLPyOxaggS+T8J6yRu5o+a0WLNmuXe7h3KreJZX36YnOgClyF5sadA1ruEI/WCK3MDvB7+3mTgHlHzcnmI6ji+4UtJG7SVchirlqdybic51YwxmVJX+TgpO7GD5cOSQWV4CoaFamj/uM6dYWaOoT9fuE6de5LV+sc65spvhonRzVR5txcFZe/bU0XPlVc6B4pwchlYy1tmzGzIEIMNjMe4zcngfwjEjDzKDceBRvs3zLezwby0fD1ELppMPx7AKKC4KTVOV63awEEvt5QmcD87B03WNVA5N/L3VrJx1b+wld9l5DTa8YmecuMuUrz8qBA5veTTi4924XMUjR4R+C0ueg/y49gLWh83mZmlE+epeSLZVKDmvtFkI2XqlvvjUVMx7wJ+YNbuT8exTArFnBhGlL5GpkrxnSSoSqhgLrxuEpThtx7DBZofFUfPZX1nUjkMFWEkZ9ieF17hvs4h+95lkJO5pEpWHhmdzTBqmKL8dIjHETKi9NOA/wu1Of1UZtcytLNazHQEgqLLi5MQ8RAh9joy48DPu3lJHryFJr+A1EQK3fuFjlj7xILF5JF4GyA54kLln4G+2AFNtydZh21A6ql2lm637Z2Khc2I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
