travis:
  secure:
    BINSTAR_TOKEN: Y9wDOk7PDeFMz1OJQu2RV8NFzGL/rh9mjikFcGNrt2lS9OBqhaZq/z0cH00cKPUN5uJY46DJjQvkRGC73gUVeBxA4NiudvIpnNkUpddpgFUHzIMg2mXhHgSWoC0AcrvGcu6v3PiBFzi/62Wn9uyrfV4N+rOmC8pzSPBqxgmRdfasBKtmeYXlOmQDcz104LN8sjDbmKP6gR3UcEGJIFdI8EKlW1THqxJ8KRyWLkAvcItTC7vT9zDYdGHqQX0mbf/+opSZV3Ga3mszBWsXw7Rt0EDXjeKzkD1JBPhIYjCrBrSdmOOUFO9zm3M6aKkf/vARDiIfXFiAp9CaYbvlNo9V4D673YkKchT7XSD3tLbSpQtHMk1pcpGrl4IizwtgXiPUB3RjYO7w24FeZTRDRQW8PNkqls/e1Ke5Fwj+exnesbagAOO5rb3NgsD6J7qDhpOzMN/WUmCM3+hTEQu1gs1rvEBsRa+QoYSF97RqLKoWC6w5w1BJGhCzOdFdjFhm9vsCU4kzuptHTYzBFnT94BOs3aVi99hkbg72ifCkn1erl6R1AENzRwouR8pNhhYGs3ktYM8wG8Bz8O/mhViImIoGxdo8Yxz9PndCKGFhW2oUuiU+tZmq6NKWgHcBj5Q36ON+kP4AL63o05XfGbgAqwBxuUaCcBVdiwE/M4ZPDO2/I9E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
